### ISSUE TITLE
Add doxygen css template

### ISSUE THREAD

**Issue by takev** [hikogui/hikogui.github.io#3]
Maybe we can copy the following to start with:
[doxygen-awesome-css](https://jothepro.github.io/doxygen-awesome-css/)

**Comment by takev** [comment]
Lets look at: https://hdoc.io/blog/open-sourcing-hdoc/

**Comment by jakoch** [comment]
I gave the doxygen-awesome-css theme a test run: https://jakoch.github.io/ttauri-project.github.io/docs/ttauri/0.3.0/index.html
If you decide for it, then he dropdown warning messages need a better position and color adjustment to match the dark theme.

**Comment by takev** [comment]
Lets to this.
If you make a pull request I will merge it.
